version: 1.0.0
compose-app: docker-compose
service-groups:
  - name: default
    project-name: arx
    compose-path: containers/compose.yaml
    env-file: .env
    services:
      default: arx
      list:
        - name: arx
