default_stages:
  - commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
    - entry: clang-format
      exclude: ^$
      files: ""
      id: clang-format
      language: system
      name: clang-format
      pass_filenames: true
      stages:
        - commit
      types_or: [c++, c]
      args: ["-style=file", "-i"]

    - entry: cppcheck
      id: cppcheck
      name: cppcheck
      language: system
      exclude: ^$
      files: "arx/"
      pass_filenames: true
      stages:
        - commit
      types_or: [c++, c]
      args: ["--std=c++17"]

    - entry: clang-tidy
      id: clang-tidy
      name: clang-tidy
      language: system
      exclude: ^$
      files: "arx/"
      pass_filenames: true
      stages:
        - commit
      types_or: [c++, c]
      args: ["-format-style='{BasedOnStyle: llvm, IndentWidth: 2}'"]
