default_stages:
  - commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
    - id: clang-format
      name: clang-format
      entry: clang-format -style=file -i
      exclude: ^$
      files: ""
      language: system
      pass_filenames: true
      stages:
        - commit
      types_or: [c++, c]

    - id: cppcheck
      name: cppcheck
      entry: "cppcheck --std=c++17 arx/"
      language: system
      pass_filenames: false
      stages:
        - commit
      types_or: [c++, c]

    - id: clang-tidy
      name: clang-tidy
      entry: clang-tidy
      language: system
      exclude: ^$
      files: "arx/"
      pass_filenames: true
      stages:
        - commit
      types_or: [c++, c]
      args: [
        "--format-style='{BasedOnStyle: llvm, IndentWidth: 2}'",
        "--checks=*",
        "--warnings-as-errors=*",
        "--header-filter=.*",
        "--fix-errors"
      ]

    - entry: cmake-format
      id: cmake-format
      name: cmake-format
      language: system
      exclude: ^$
      files: (\.cmake|CMakeLists.txt)(.in)?$
      pass_filenames: true
      stages:
        - commit
      types: [file]
      args: ["-i"]
