site_name: ArxLang

theme:
  name: null
  custom_dir: 'docs/theme/'

extra_css:
  - docs/theme/style.css

nav:
  - Home: 'index.md'
  - Tutorials: 'tutorials/index.md'
  - "Getting Started": 'getting-started.md'
  - Sponsor: 'sponsor.md'
  - Roadmap: 'roadmap.md'
  - Governance: 'governance.md'
  - Partners: 'partners.md'
