version: '3.4'

services:
  arx:
    hostname: arx
    build:
      context: ..
      dockerfile: containers/Dockerfile
      args:
        # note: if you want to use a specific UID and GID, ensure to add it to
        #       the .env file
        - UID=${HOST_UID:-1000}
        - GID=${HOST_GID:-1000}
    user: "arx:arx"
    volumes:
      - ..:/opt/arx
