name: arx
channels:
- nodefaults
- conda-forge
dependencies:
# build
- compilers
- compiler-rt
- clangdev 14.*
- clangxx 14.*
- cmake
- llvmdev 14.*
- ninja
# run
- arrow-cpp 7.*
- cli11
# dev
- include-what-you-use >=0.18
- doxygen
- cmake-format
- cppcheck
- glog
- gmock
- gtest
- lcov
- nodejs
- pre-commit
