name: arx
channels:
- nodefaults
- conda-forge
dependencies:
# build
- compilers
- compiler-rt
- clangdev 13.*
- clangxx 13.*
- cmake
- llvmdev 13.*
- lld 13.*
- meson
- ninja
- pkg-config
# run
- arrow-cpp 8.*
- arrow-c-glib 8.*
- cli11
- glog
# dev
- include-what-you-use >=0.18
- cmake-format
- cppcheck
- doxygen
- gmock
- gtest
- lcov
- nodejs
- pre-commit
