name: arx
channels:
- nodefaults
- conda-forge
dependencies:
# build
- compilers
- compiler-rt
- clangdev 13.*
- clangxx 13.*
- cmake
- llvmdev 13.*
- ninja
# run
- arrow-cpp 7.*
- cli11
# dev
- pre-commit
- nodejs
- gtest
- gmock
- glog
- lcov
- cmake-format
- doxygen
- cppcheck
