name: arx
channels:
- nodefaults
- conda-forge
dependencies:
- arrow-cpp 7.*
- compilers
- compiler-rt
- clangdev 13.0.1
- clangxx 13.0.1
- cmake
- llvmdev 13.0.1
- ninja
# dev
- pre-commit
- nodejs
- gtest
- gmock
