{% set name = "arx" %}
{% set version = "1.3.0" %}  # semantic-release
{% set llvm_version = "13.*" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../..

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.21
    - ninja
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - arrow-cpp 7.*
    - cli11
    - clangdev {{ llvm_version }}
    - libclang-cpp {{ llvm_version }}
    - lld {{ llvm_version }}
    - llvm {{ llvm_version }}
    - llvmdev {{ llvm_version }}

test:
  require:
    - gtest
  commands:
    - arx --version

about:
  home: https://github.com/arx-org/arx
  license: Apache-2.0
  license_family: Apache
  summary: Arx compiler aims to provide arrow datatypes as native datatypes.
  description: |
    Arx compiler aims to provide arrow datatypes as native datatypes.
    For now, it is strongly based on Kaleidoscope compiler with a few changes.
    **ROADMAP**
    * Implement more datatypes
      * int8, int16, int32, int64
      * float16, float32, float64
      * string
      * datetime
    * Change the language design (syntax)
    * Implement arrow datatypes as native datatypes
  doc_url: https://github.com/arx-org/arx
  dev_url: https://github.com/arx-org/arx

extra:
  recipe-maintainers:
    - xmnlab
