site_name: ArxLang

docs_dir: ./
site_dir: ../build/docs

theme:
  name: null
  custom_dir: 'theme/'
  logo: 'images/arx.png'
  favicon: 'favicon.ico'

extra:
  homepage: https://arxlang.org

extra_css:
  - theme/style.css

nav:
  - Home: 'index.md'
  - Tutorials:
    - main: 'tutorials/index.md'
    - 'Getting Started': 'tutorials/Getting-Started.ipynb'
  - 'Getting Started': 'getting-started.md'
  - 'API Doc': '/api/'
  - Sponsor: 'sponsor.md'
  - Roadmap: 'roadmap.md'
  - Governance: 'governance.md'
  - Partners: 'partners.md'
  - Code of Conduct: 'coc.md'

plugins:
  - mkdocs-jupyter
