name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  conda-build:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    concurrency:
      group: ci-build-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        miniforge-variant: Mambaforge
        channels: conda-forge,nodefaults
        channel-priority: true
        activate-environment: arx-build
        environment-file: conda/build.yaml

    - name: build using conda
      run: make conda-build
