name: containers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  containers:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    concurrency:
      group: ci-containers-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive


    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        miniforge-variant: Mambaforge
        channels: conda-forge,nodefaults
        channel-priority: true
        activate-environment: arx-containers
        environment-file: conda/containers.yaml

    - name: create a dot env file
      run: |
        makim env.create-file
        cat .env

    - name: build container
      run: containers-sugar build

    - name: run container
      run: |
        # TODO: build arx using containers-sugar
        containers-sugar run --service arx --options '--rm' --cmd "makim build.release"
