# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: containers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  containers:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    concurrency:
      group: ci-containers-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive


    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        miniforge-variant: Mambaforge
        channels: conda-forge,nodefaults
        channel-priority: true
        activate-environment: arx-containers
        environment-file: conda/containers.yaml

    - name: build container
      run: containers-sugar build

    - name: run container
      run: |
        # TODO: build arx using containers-sugar
        containers-sugar run --services arx --extras='--rm' --cmd "makim build.release"
