name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    concurrency:
      group: ci-main-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive


    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        miniforge-variant: Mambaforge
        channels: conda-forge,nodefaults
        channel-priority: true
        activate-environment: arx
        environment-file: conda/dev-linux-64.yaml

    - name: build
      run: makim build.dev --clean

    - name: test flags
      run: build/arx --version

    - name: run sanity tests
      run: makim tests.sanitizer

    - name: run example tests
      run: makim tests.gen-all-examples

    - name: lint
      if: success() || failure()
      run: |
        pre-commit install
        makim tests.lint

    - name: llvm-cov generation
      if: ${{ github.event_name == 'pull_request' }}
      id: llvm-cov-report
      run: makim tests.code-coverage

    - name: Semantic Release PR Title Check
      uses: osl-incubator/semantic-release-pr-title-check@v1.4.1
      if: ${{ github.event_name == 'pull_request' && (always() || failure()) }}
      with:
        convention-name: conventionalcommits
