# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    concurrency:
      group: ci-main-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive


    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        mamba-version: "*"
        channels: conda-forge,nodefaults
        channel-priority: true
        activate-environment: arx
        environment-file: conda/dev-linux-64.yaml

    - name: build
      run: make build-with-tests CLEAN=1

    - name: test flags
      run: |
        build/arx --version

    - name: run sanity tests
      run: make test-sanitizer

    # NOTE: AddressSanitizer:DEADLYSIGNAL
    #  =================================================================
    #  ==5570==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000
    #   (pc 0x0000003a1ef7 bp 0x7ffc95ff93d0 sp 0x7ffc95ff93d0 T0)
    #  ==5570==The signal is caused by a READ memory access.
    #  ==5570==Hint: address points to the zero page.
    #      #0 0x3a1ef7 in llvm::DIScope::getRawFile() const codegen.cpp
    #      #1 0x39313b in FunctionAST::codegen() (/home/runner/work/arx/arx/build/arx+0x39313b)
    #      #2 0x395f4d in HandleDefinition() (/home/runner/work/arx/arx/build/arx+0x395f4d)
    #      #3 0x396904 in MainLoop() (/home/runner/work/arx/arx/build/arx+0x396904)
    #      #4 0x398bf6 in compile() (/home/runner/work/arx/arx/build/arx+0x398bf6)
    #      #5 0x3c5a7a in main (/home/runner/work/arx/arx/build/arx+0x3c5a7a)
    #      #6 0x7fc26d90a082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082)
    #      #7 0x29c0a8 in _start (/home/runner/work/arx/arx/build/arx+0x29c0a8)
    #
    #  AddressSanitizer can not provide additional info.
    #  SUMMARY: AddressSanitizer: SEGV codegen.cpp in llvm::DIScope::getRawFile() const
    #- name: test examples
    #  run: make test-examples

    - name: lint
      run: |
        pre-commit install
        pre-commit run --all-files

    - name: llvm-cov generation
      if: ${{ github.event_name == 'pull_request' }}
      id: llvm-cov-report
      run: make code-coverage

    - name: Check if PR title is a correct semantic-release prefix
      if: ${{ github.event_name == 'pull_request' && always() }}
      run: bash scripts/ci/pr-title-check.sh "${{ github.event.pull_request.title }}"
