# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            conda_env_file: dev-linux-64.yaml
          - os: macos-latest
            conda_env_file: dev-osx-64.yaml

    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    concurrency:
      group: ci-main-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive


    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        mamba-version: "*"
        channels: conda-forge,nodefaults
        channel-priority: true
        activate-environment: arx
        environment-file: conda/${{ matrix.conda_env_file }}

    - name: build
      run: make build-dev CLEAN=1

    - name: test flags
      run: |
        build/arx --version

    - name: run sanity tests
      run: make test-sanitizer

    - name: run example tests
      run: make test-examples

    - name: lint
      run: |
        pre-commit install
        pre-commit run --all-files

    - name: llvm-cov generation
      if: ${{ github.event_name == 'pull_request' }}
      id: llvm-cov-report
      run: make code-coverage

    - name: Check if PR title is a correct semantic-release prefix
      if: ${{ github.event_name == 'pull_request' && always() }}
      run: bash scripts/ci/pr-title-check.sh "${{ github.event.pull_request.title }}"
