# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive


    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        mamba-version: "*"
        channels: conda-forge,nodefaults
        channel-priority: true
        activate-environment: arx
        environment-file: conda/dev.yaml

    - name: Install release dependencies
      run: mamba env update -n arx --file conda/release.yaml

    - name: build code
      run: make build

    - name: Test documentation generation
      run: make docs-build

    - name: Test release
      if: ${{ github.event_name != 'workflow_dispatch' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make release-dry

    # note: semantic-release should be executed before the documentation
    #       publishing because semantic-release will update changelog and
    #       update hard-coded version inside some files
    - name: Release
      if: ${{ github.event_name == 'workflow_dispatch' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make release

    - name: Generate documentation with changes from semantic-release
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: make docs-build

    - name: GitHub Pages action
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/
